language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12

addons:
  apt:
    sources:
    	- github-git-lfs-xenial
    packages:
    	- git-lfs
      
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
